%\VignetteIndexEntry{bioCancer Vignette}
%\VignetteEngine{R.rsp::tex}
%\VignetteAuthor{Karim Mezhoud}
\documentclass[a4paper]{article}
%\usepackage[OT1]{fontenc}
\usepackage{zi4}
%\usepackage{Sweave}
\usepackage{url}
\usepackage[pdftex,plainpages=true,pdfpagelabels, colorlinks=true ,urlcolor= blue, linkcolor= red, citecolor=magenta]{hyperref}
\usepackage{graphicx}
\usepackage{amsmath}
\usepackage[margin=1in]{geometry}
\setkeys{Gin}{width=0.9\textwidth} % set figures width (this is the default)
\begin{document}
%\SweaveOpts{concordance=TRUE}
%\SweaveOpts{concordance=TRUE}


\title{bioCancer: Multi-Omics Cancers data Visualisation and Analysis}
\author{Karim Mezhoud}
\date{January 12, 2016}
\maketitle

\section{Portal Panel}
\subsection{Display available Cancer Studies in Table}

\subsubsection{Studies Panel}

This panel displays in table all available cancer studies hosted and maintained by Memorial Sloan Kettering Cancer Center (\url{(https://www.mskcc.org)}). It provides access to data by The Cancer Genome Atlas as well as many carefully curated published data sets.

Every row lists one study by `Identity`, `name` and `description`.

\paragraph{Browse the data}

By default only 10 rows of are shown at one time. You can change this setting through the `Show ... entries` dropdown. Press the `Next` and `Previous` buttons at the bottom-right of the screen to navigate through the data.


\paragraph{Sort}

Click on a column header in the table to sort the data by the values of that variable. Clicking again will toggle between sorting in ascending and descending order. To sort on multiple columns at once press shift and then click on the 2nd, 3rd, etc. column to sort by.

\subsubsection{Filters in Table}
The search is possible for numerical or categorical variables. It is possible to match `string` or to use mathematical `operator` to filter data. For more detail see help page in Handle > View panel.
\paragraph{ Global Search}
the `Filter` box on the left (click the check-box first).
\paragraph{ Column filter}
Every column has its filetr at the column header.

\subsubsection{Download table as csv file}
User can download table as csv file. Use the download icon in the top-right of the page.



%%%%%
\end{document}
